In [13]:
import pandas as pd

In [14]:
df = pd.read_csv('clustering_v2.csv')

In [15]:
df

,sembrada,cosechada,siniestrada,volumenproduccion,latitud,longitud,altitud,cicloproductivo_Otoño-Invierno,cicloproductivo_Perennes,cicloproductivo_Primavera-Verano,...,modalidad_Temporal,cultivo_Avena forrajera en verde,cultivo_Frijol,cultivo_Maíz grano,cultivo_Pastos y praderas,cultivo_Tomate rojo (jitomate),K=8 Cluster Labels,rendimiento,cultivo,estado
0,35012.00,35012.00,0.0,401061.32,24.767219,-107.696760,12.0,1,0,0,...,0,0,0,1,0,0,7,11.45,Maíz grano,Sinaloa
1,1302.00,1302.00,0.0,108818.40,31.808944,-116.595134,18.0,0,0,1,...,0,0,0,0,0,1,4,83.58,Tomate rojo (jitomate),Baja California
2,30597.34,30597.34,0.0,361643.68,25.783417,-108.994343,9.0,1,0,0,...,0,0,0,1,0,0,7,11.82,Maíz grano,Sinaloa
3,30816.00,30816.00,0.0,364810.83,24.808808,-107.393756,57.0,1,0,0,...,0,0,0,1,0,0,7,11.84,Maíz grano,Sinaloa
4,2331.00,2331.00,0.0,232416.02,24.808808,-107.393756,57.0,1,0,0,...,0,0,0,0,0,1,4,99.71,Tomate rojo (jitomate),Sinaloa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11247,11.00,0.00,11.0,0.00,24.048799,-98.900294,149.0,0,0,1,...,0,0,0,0,0,1,4,0.00,Tomate rojo (jitomate),Tamaulipas
11248,10.00,0.00,10.0,0.00,23.301759,-99.547539,1263.0,1,0,0,...,1,1,0,0,0,0,0,0.00,Avena forrajera en verde,Tamaulipas
11249,1415.00,0.00,1415.0,0.00,19.638472,-97.103496,2420.0,0,0,1,...,1,0,0,1,0,0,6,0.00,Maíz grano,Veracruz
11250,1210.00,0.00,1210.0,0.00,19.664859,-97.001371,1746.0,0,0,1,...,1,0,0,1,0,0,6,0.00,Maíz grano,Veracruz
11251,0.50,0.00,0.5,0.00,21.567599,-88.232063,12.0,1,0,0,...,0,0,0,0,0,1,4,0.00,Tomate rojo (jitomate),Yucatán

In [16]:
df.columns

Index(['sembrada', 'cosechada', 'siniestrada', 'volumenproduccion', 'latitud',
       'longitud', 'altitud', 'cicloproductivo_Otoño-Invierno',
       'cicloproductivo_Perennes', 'cicloproductivo_Primavera-Verano',
       'modalidad_Riego', 'modalidad_Temporal',
       'cultivo_Avena forrajera en verde', 'cultivo_Frijol',
       'cultivo_Maíz grano', 'cultivo_Pastos y praderas',
       'cultivo_Tomate rojo (jitomate)', 'K=8 Cluster Labels', 'rendimiento',
       'cultivo', 'estado'],
      dtype='object')

In [17]:
df.rename(columns = {"cultivo_Tomate rojo (jitomate)":"cultivo_Tomate rojo"}, inplace=True)

In [18]:
df

,sembrada,cosechada,siniestrada,volumenproduccion,latitud,longitud,altitud,cicloproductivo_Otoño-Invierno,cicloproductivo_Perennes,cicloproductivo_Primavera-Verano,...,modalidad_Temporal,cultivo_Avena forrajera en verde,cultivo_Frijol,cultivo_Maíz grano,cultivo_Pastos y praderas,cultivo_Tomate rojo,K=8 Cluster Labels,rendimiento,cultivo,estado
0,35012.00,35012.00,0.0,401061.32,24.767219,-107.696760,12.0,1,0,0,...,0,0,0,1,0,0,7,11.45,Maíz grano,Sinaloa
1,1302.00,1302.00,0.0,108818.40,31.808944,-116.595134,18.0,0,0,1,...,0,0,0,0,0,1,4,83.58,Tomate rojo (jitomate),Baja California
2,30597.34,30597.34,0.0,361643.68,25.783417,-108.994343,9.0,1,0,0,...,0,0,0,1,0,0,7,11.82,Maíz grano,Sinaloa
3,30816.00,30816.00,0.0,364810.83,24.808808,-107.393756,57.0,1,0,0,...,0,0,0,1,0,0,7,11.84,Maíz grano,Sinaloa
4,2331.00,2331.00,0.0,232416.02,24.808808,-107.393756,57.0,1,0,0,...,0,0,0,0,0,1,4,99.71,Tomate rojo (jitomate),Sinaloa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11247,11.00,0.00,11.0,0.00,24.048799,-98.900294,149.0,0,0,1,...,0,0,0,0,0,1,4,0.00,Tomate rojo (jitomate),Tamaulipas
11248,10.00,0.00,10.0,0.00,23.301759,-99.547539,1263.0,1,0,0,...,1,1,0,0,0,0,0,0.00,Avena forrajera en verde,Tamaulipas
11249,1415.00,0.00,1415.0,0.00,19.638472,-97.103496,2420.0,0,0,1,...,1,0,0,1,0,0,6,0.00,Maíz grano,Veracruz
11250,1210.00,0.00,1210.0,0.00,19.664859,-97.001371,1746.0,0,0,1,...,1,0,0,1,0,0,6,0.00,Maíz grano,Veracruz
11251,0.50,0.00,0.5,0.00,21.567599,-88.232063,12.0,1,0,0,...,0,0,0,0,0,1,4,0.00,Tomate rojo (jitomate),Yucatán

## Connect to the database

In [19]:
from config import DATABASE_URI

In [20]:
# Import psycopg2 which is the PostgreSQL adapter for Python
# documentation https://www.psycopg.org/docs/install.html#install-from-source

In [21]:
#pip install psycopg2-binary

In [22]:
from sqlalchemy import create_engine
import psycopg2

In [23]:
# create engine
engine = create_engine(DATABASE_URI)

In [24]:
# convert the dataframe into a sql table with pd.to_sql function
df.to_sql(con= engine, name='clustering', index=False, if_exists = "replace")